- name: copying the {{COMPONENT}} repo 
  ansible.builtin.copy:
     src: mongodb.repo 
     dest: /etc/yum.repos.d/mongodb.repo 

- name: Installing {{COMPONENT}} 
  ansible.builtin.package:
    name: mongodb-org  
    state: present 

- name: Updating {{COMPONENT}} Listening Config 
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Starting {{COMPONENT}} 
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes  

- name: Download and extracting {{COMPONENT}} from github
  ansible.builtin.include_role:
    name: common 
    tasks_from: download-from-github 

- name: Loading Catalogue and Users Scahme 
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}.js"
    idempotent: yes
  loop: 
    - catalogue 
    - users

# Ensure you run this at the end of all the tasks only.
- name: Set-hostname 
  ansible.builtin.include_role:
    name: common 
    tasks_from: set-hostname 

- name: Adding the the task indicating that the mongodb config is completed 
  debug: 
    msg: Mongodb COnfig is Completed